### ISSUE TITLE
Pagination Redesign

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#1]
its in v4 project > collection page > large viewport

https://preview.uxpin.com/f18c179bba6bc08730787ab22eb1050628a9a2ae#/pages/67483193?mode=cmd

<img width="1282" alt="screen shot 2017-03-30 at 12 26 51 pm" src="https://cloud.githubusercontent.com/assets/3649059/24515057/61c88f7c-1544-11e7-8299-f5d4e78cc635.png">

**Comment by JenSparks** [comment]
@GVFTW Updated!
