### ISSUE TITLE
Variant Price Displaying Incorrect

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#10]
Should read $77

https://alala-dev.myshopify.com/products/captain-ankle-tight-liquid?variant=31736891401

<img width="1204" alt="screen shot 2017-04-01 at 10 06 48 pm" src="https://cloud.githubusercontent.com/assets/3649059/24583886/8bd9bf18-1727-11e7-86de-3ea823880b2a.png">

**Comment by JenSparks** [comment]
@GVFTW This appears to be correct -- can you confirm? Perhaps the product data was corrupt is all? I know Avery has been making catalog changes...

**Comment by GVFTW** [comment]
@JenSparks liquid black should be full price ($110), liquid indigo should be on sale ($77)
https://alala-dev.myshopify.com/admin/products/8946947337

<img width="703" alt="screen shot 2017-04-06 at 10 44 24 am" src="https://cloud.githubusercontent.com/assets/3649059/24760263/2a5de600-1ab6-11e7-9b7c-579ad8f4457e.png">

**Comment by JenSparks** [comment]
@GVFTW Thanks for clarifying. We've got this dialed in now - we were just missing the right ID in the callback. Should be good now.
