### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#2]
**On Large**
one-twelfth 
- breadcrumb
- previous product arrow

one-half
- product image (padding-right: 60px)

one-third
- product title and info

one-twelfth
- next product arrow

<img width="1280" alt="screen shot 2017-03-23 at 4 54 59 pm" src="https://cloud.githubusercontent.com/assets/3649059/24270105/2b2261e6-0fea-11e7-9f21-1b05ad8b1344.png">

--------------------------------

On XL

**Comment by JenSparks** [comment]
@GVFTW Updated.

The page's LARGE grid is defined as follows:

one-twelfth
six-twelfths
four-twelfths

Which leaves one-twelfth for the right side where the Next-product Arrow resides.
