### ISSUE TITLE
Breadcrumb and Prev/Next Arrows

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#3]
Hide **on mobile**

**Comment by JenSparks** [comment]
@GVFTW Updated. Assuming you meant the product image carousel... We removed the prev/next arrows on mobile only. The breadcumb menu was already hidden though unless we're talking about different things.

**Comment by GVFTW** [comment]
Hmm I should have screenshotted, that's my bad. At the time, page was showing prev/next arrows (the ones we use to browse thru the parent collection) in an odd space. They're gone now though, so we're all good.
