### ISSUE TITLE
"Wear & Share" Carousel

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#4]
What you guys have up on the product page now is the "Visual UGC"

What we'd like styled out in this section is the "Photo Carousel" (I know, Yotpo sucks)

More info -
https://yap.yotpo.com/#/tools/pictures_slider

> The Photos Carousel displays customer-uploaded and socially curated photos on product pages. The Carousel will display if you have at least three published photos for a given product. You can choose which photos to publish from Moderation.
> 
> It’s recommended to put this widget above the fold in order to maximize conversions on product pages. It lets shoppers easily click through authentic photos to see how products look in real life.

**Comment by JenSparks** [comment]
@GVFTW Updated.

However without photos in Yotpo for any product, there's no good way to test this. We added some CSS so this degrades OK when no images are displayed but we haven't been able to test what this looks like when there are actual photos.

**Comment by GVFTW** [comment]
@Aves3888 see Jen's comment above. We need to figure out a way to tag dev products in yotpo in order for images to show up on new templates. 

Is this because they have different product IDs now? Is there anyway for us to pull 1 manually so we can preview styling in dev?

@JenSparks we'll work on getting some content to populate photos carousel and let you know when its up.

**Comment by GVFTW** [comment]
@JenSparks we should have everything set on our end. 

We have the Alpine Tight ( https://alala-dev.myshopify.com/collections/shoppad/products/alpine-tight?variant=31736720521 ) tagged in 4 items in our Yotpo curation feed using product ID 8946939337 but the feed is not showing up on the product page quite yet. 

Here's the link to Curation in case you need to experiment - 
https://yap.yotpo.com/#/moderation/curation

Please let me know if there's anything else on our end we should do to get it working. Thanks!

**Comment by JenSparks** [comment]
@GVFTW Done. However, on large screens where the image dimensions for these are 400x400 max, the image resolution looks pixelated because the images sent from Yotpo are only 150x150. There doesn't seem to be any configuration controls or setting to change unfortunately.

**Comment by GVFTW** [comment]
@Aves3888 see above. can you get with Lihi and find out if there's a way to resolve this?

here's what it looks like now -
<img width="1588" alt="screen shot 2017-04-06 at 10 48 57 am" src="https://cloud.githubusercontent.com/assets/3649059/24760494/d63b148e-1ab6-11e7-830f-18a6eed238a9.png">

**Comment by Aves3888** [comment]
YOTPO has advised on the pixelation/size issue:

This should be placed in the shopify theme after the widget snippet. If there are any issues with it, try the second one (bigger dimensions).

jQuery('.y-image-wrapper img').each(function(a,b){
	b.src = b.src.replace('s150x150','s370x370')
})


jQuery('.y-image-wrapper img').each(function(a,b){
	b.src = b.src.replace('s150x150','s640x640')
})

**Comment by JenSparks** [comment]
@Aves3888 @GVFTW The Yotpo widget has been updated to show the higher resolutions images.
