### ISSUE TITLE
Add Review Count to Stars

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#7]
add review count and style per mockup (stars are sharper and a bit smaller)

<img width="131" alt="screen shot 2017-03-23 at 5 55 57 pm" src="https://cloud.githubusercontent.com/assets/3649059/24272093/191721dc-0ff2-11e7-827f-7c3668f97f35.png">

**Comment by JenSparks** [comment]
@GVFTW Updated.

However, we can't change the markeup sent from Yotpo so the closest we can get it is like this:
https://www.dropbox.com/s/urxtz6kgrv6j6fj/Screenshot%202017-03-30%2008.54.46.png?dl=0
