### ISSUE TITLE
Compare Price / Product Price

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#8]
Add some space in between per mockup

looks like
<img width="107" alt="screen shot 2017-03-23 at 6 11 38 pm" src="https://cloud.githubusercontent.com/assets/3649059/24272577/446b64f4-0ff4-11e7-9b0d-affe058e8450.png">

should look like
<img width="125" alt="screen shot 2017-03-23 at 6 12 36 pm" src="https://cloud.githubusercontent.com/assets/3649059/24272594/541b0314-0ff4-11e7-928e-a8a2f49ab715.png">

**Comment by JenSparks** [comment]
@GVFTW This has been updated. Added 10px margin to the right of the strike-through price.
