### ISSUE TITLE
Feat. Image Carousel 

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/product-template#9]
display only selected variant images

**Comment by GVFTW** [comment]
Image not displaying on Chrome Version 57.0.2987.98

<img width="1535" alt="screen shot 2017-03-27 at 11 00 40 am" src="https://cloud.githubusercontent.com/assets/3649059/24363267/581f6784-12dd-11e7-9aa3-5fe44c84c7eb.png">

**Comment by JenSparks** [comment]
The image isn't showing because the images ALT tags needs to be updated for this product (and across the entire catalog) to match the swatch names.

We went ahead and updated the ALT tags for this particular product but this should be done in the spreadsheet across the entire catalog.

**Comment by GVFTW** [comment]
@JenSparks thanks! 

What is our solution for viewing the alternate images within the same color variant? This is an important feature that we can't afford to lose.

**Comment by JenSparks** [comment]
@GVFTW You can still have alternate images appear for the same color variant. As long as the ALT tags are the same, the images will appear in a carousel. See the Captain Ankle Tight as an example:

https://alala-dev.myshopify.com/collections/shoppad/products/captain-ankle-tight?variant=31736882825

**Comment by GVFTW** [comment]
@JenSparks ahh ok, great! thanks
